name: tomkums
favicon: null
layout_spectrum: 0.4394786807242781
typography_spectrum: 0.4963482606690377
title: Tom Kums
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7048176168464124
  lightness: 0.012132702860981226
  saturation: 0.8614909921307117
  rhythmicContrast: 0.8404482954647392
purpose: []
