name: tomkums
favicon: null
layout_spectrum: 0.23657
typography_spectrum: 0.30244
title: Tom Kums
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#ffffff'
    - '#5b5b5b'
    - '#929292'
    - '#b5b5b5'
  brandStrength: 0.7048176168464124
  lightness: 0.012132702860981226
  saturation: 0.8614909921307117
  rhythmicContrast: 0.8404482954647392
purpose: []
